apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-ethereum-exporter.fullname" . }}
  labels:
{{ include "prometheus-ethereum-exporter.labels" . | indent 4 }}
spec:
  jobLabel: {{ .Chart.Name }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus-ethereum-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: exporter
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- end }}
{{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.serviceMonitor.metricRelabelings | indent 4) . }}
{{- end }}
{{- if .Values.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.serviceMonitor.relabelings | indent 4 }}
{{- end }}
